export const skillNamesArr = [
  { id: "html5", title: "HTML5" },
  { id: "css3", title: "CSS3" },
  { id: "js", title: "JS(ES6)" },
  { id: "react", title: "React" },
  { id: "redux", title: "Redux" },
  { id: "sass", title: "SASS" },
  { id: "postcss", title: "PostCSS" },
  { id: "bootstrap", title: "Bootstrap" },
  { id: "nodejs", title: "Node.js" },
  { id: "mongodb", title: "MongoDB" },
  { id: "git", title: "Git" },
  { id: "github", title: "Github" },
  { id: "vite", title: "Vite" },
  { id: "nextjs", title: "Next.js" },
  { id: "tailwind", title: "Tailwind" },
  { id: "netlify", title: "Netlify" },
  { id: "heroku", title: "Heroku" },
  { id: "aws", title: "AWS" },
  { id: "jest", title: "Jest" },
  { id: "githubactions", title: "Github Actions" },
  { id: "vim", title: "Vim" },
];
